source 'https://rubygems.org'
ruby '>= 2.4.0'

gem 'rails', '4.2.8'
gem 'sass-rails', '~> 5.0'
# gem 'bootstrap-sass'
gem 'honoka-rails'
gem 'uglifier'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
# gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem 'rails-i18n'
gem 'kaminari'
gem 'puma'
gem 'enumerize'
gem 'js_cookie_rails'
gem 'babel-transpiler'

group :test do
  gem 'factory_girl_rails'
  gem 'minitest-reporters'
  gem 'mini_backtrace'
  gem 'guard-minitest'
end

group :development do
  gem 'sqlite3'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'byebug'
  gem 'guard'
  gem 'railroady'
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'annotate'
  gem 'bullet'
  gem 'faker'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end
